### ISSUE TITLE
Getting a "rockchip-pinctrl pinctrl: invalid function gpio in map table" message on bootup

### ISSUE THREAD

**Issue by Gerriko** [radxa/overlays#88]
I am using a rk3566 chip.
I was using the "rk3568-spi3-m1-cs0-enc28j60.dts" overlay file as my reference but I am using GPIO4_A3 as my interrupt pin.

I have used the following for pinctrl:

```
	fragment@2 {
		target = <&pinctrl>;

		__overlay__ {
			enc28j60 {
				eth0_pins: eth0-pins {
					rockchip,pins = <4 3 0 &pcfg_pull_none>;
				};
			};

		};
	};

```

Can any explain what is wrong with `rockchip,pins = <4 3 0  &pcfg_pull_none>;`

**Comment by Gerriko** [comment]
I tried an override command as follows:

```
	__overrides__ {
		int_pin = <&eth0>, "interrupts:0", <&eth0_pins>, "rockchip,pins:0";
		speed = <&eth0>, "spi-max-frequency:0";
	};

```
And then I got this message in the debug output on bootup:

![image](https://github.com/radxa/overlays/assets/11910146/9d799643-4f26-4d08-8ce5-0e9f8b3e6dd2)

So why is fe6b0000.serial holding onto gpio4-3?

**Comment by RadxaYuntian** [comment]
Coding problem should go to our forum. The issues here should be if one of our supplied overlays doesn't work.

Regarding your problem though, here is how you tackle it:

1. Find the offending serial's phandle: [UART7](https://github.com/radxa/kernel/blob/stable-4.19-rock3/arch/arm64/boot/dts/rockchip/rk3568.dtsi#LL3000C2-L3000C7)

2. Realize none of our products uses UART7, so this is either a custom system, a custom hardware, or both.

Well there is nothing I can help because I don't know why you use UART7 on your product /shrug You should check your own design then.
